server:
  port: 8888
logging:
  file:
    path: logs
spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo01
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.szh.model
  mapper-locations:
    - mapper/*